version: '3.8'

services:
  rag-civia-mandate-service:
    image: luisorellanaa/rag-civia-mandate-service:0.2.3-SNAPSHOT
    ports:
      - "8088:8088"
    restart: always
    environment:
      DB_CLUSTER: ""
      DB_KEY: ""
      DB_USER: ""
      DB_NAME: ""
      GEMINI-KEY: ""