services:
  rag-civia-mandate-service:
    image: luisorellanaa/rag-civia-mandate-service:0.4.1-SNAPSHOT
    ports:
      - "8088:8088"
    restart: always
    environment:
      DB_CLUSTER: ""
      DB_KEY: ""
      DB_USER: ""
      DB_NAME: ""
      GEMINI_KEY: ""
      OPENCAGE_KEY: ""