spring:
  application:
    name: civia
  data:
    mongodb:
      uri: "mongodb+srv://${DB_USER}:${DB_KEY}@${DB_CLUSTER}.ppdci.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: ${DB_NAME}
server:
  port: 8081
integration:
  gemini:
    system-instruction: "Solo utiliza español. No alucines. Eres un sistema de recomendación de tareas para municipalidades. Tu función es analizar una lista de tareas históricas. Cada una con una descripción, una puntuación numérica de costo (cuanto menor, mejor) y una de beneficio (cuanto mayor, mejor), y a partir de estos datos, clasifica las nuevas tareas entrantes (que carecen de estos puntajes) según su potencial costo-beneficio. Utiliza los siguientes datos históricos como referencia:\n\n
    <HISTORY_MANDATES_LIST> \n
    Analiza las tareas históricas para detectar patrones de bajo costo y alto beneficio. Luego, compara las tareas entrantes ingresadas por el usuario y asigna a cada una estimación numérica de costo (inferredCost) y beneficio (inferredBenefit), además de clasificarlas en prioridad según una escala de 7 niveles (Crítica, Muy alta, Alta, Media, Baja, Muy baja, Mínima). En la respuesta incluye exactamente las mismas tareas que el usuario ha ingresado. Solo responde en formato JSON utilizando el siguiente formato: \n
    Mandate = {\"request\": str, \"inferredCost\": str, \"inferredBenefit\": str, \"priority\": str, \"explanation\": str}
    Return: list[Mandate]"